import { isTextSourcePath } from './fileTypes';

/**
 * Lightweight MIME-type lookup keyed by extension.
 * Used to wrap blobs in a `Blob(..., { type })` so e.g. blob URLs used as
 * stylesheets are parsed as CSS, and SVGs are recognised as images.
 */
const MIME_BY_EXT: Record<string, string> = {
  html: 'text/html;charset=utf-8',
  htm:  'text/html;charset=utf-8',
  xhtml: 'application/xhtml+xml;charset=utf-8',
  shtml: 'text/html;charset=utf-8',
  css:  'text/css;charset=utf-8',
  scss: 'text/x-scss;charset=utf-8',
  sass: 'text/x-sass;charset=utf-8',
  less: 'text/x-less;charset=utf-8',
  styl: 'text/plain;charset=utf-8',
  stylus: 'text/plain;charset=utf-8',
  pcss: 'text/css;charset=utf-8',
  postcss: 'text/css;charset=utf-8',
  js:   'text/javascript;charset=utf-8',
  mjs:  'text/javascript;charset=utf-8',
  cjs:  'text/javascript;charset=utf-8',
  jsx:  'text/jsx;charset=utf-8',
  ts:   'text/typescript;charset=utf-8',
  mts:  'text/typescript;charset=utf-8',
  cts:  'text/typescript;charset=utf-8',
  tsx:  'text/tsx;charset=utf-8',
  json: 'application/json;charset=utf-8',
  json5: 'application/json5;charset=utf-8',
  jsonc: 'application/json;charset=utf-8',
  geojson: 'application/geo+json;charset=utf-8',
  webmanifest: 'application/manifest+json;charset=utf-8',
  webapp: 'application/x-web-app-manifest+json;charset=utf-8',
  map: 'application/json;charset=utf-8',
  xml:  'application/xml;charset=utf-8',
  yaml: 'application/yaml;charset=utf-8',
  yml:  'application/yaml;charset=utf-8',
  toml: 'application/toml;charset=utf-8',
  csv:  'text/csv;charset=utf-8',
  tsv:  'text/tab-separated-values;charset=utf-8',
  md:   'text/markdown;charset=utf-8',
  mdx:  'text/mdx;charset=utf-8',
  txt:  'text/plain;charset=utf-8',
  graphql: 'application/graphql;charset=utf-8',
  gql:  'application/graphql;charset=utf-8',
  svg:  'image/svg+xml',
  svgz: 'image/svg+xml',
  png:  'image/png',
  apng: 'image/apng',
  jpg:  'image/jpeg',
  jpeg: 'image/jpeg',
  jfif: 'image/jpeg',
  pjpeg: 'image/jpeg',
  pjp: 'image/jpeg',
  gif:  'image/gif',
  webp: 'image/webp',
  avif: 'image/avif',
  ico:  'image/x-icon',
  cur:  'image/x-icon',
  bmp:  'image/bmp',
  tif:  'image/tiff',
  tiff: 'image/tiff',
  heic: 'image/heic',
  heif: 'image/heif',
  jxl:  'image/jxl',
  jp2:  'image/jp2',
  j2k:  'image/jp2',
  jpf:  'image/jpx',
  woff: 'font/woff',
  woff2: 'font/woff2',
  ttf:  'font/ttf',
  otf:  'font/otf',
  ttc:  'font/collection',
  otc:  'font/collection',
  eot:  'application/vnd.ms-fontobject',
  pdf:  'application/pdf',
  rtf:  'application/rtf',
  mp4:  'video/mp4',
  m4v:  'video/x-m4v',
  webm: 'video/webm',
  ogv:  'video/ogg',
  mov:  'video/quicktime',
  avi:  'video/x-msvideo',
  mp3:  'audio/mpeg',
  m4a:  'audio/mp4',
  aac:  'audio/aac',
  oga:  'audio/ogg',
  ogg:  'audio/ogg',
  opus: 'audio/opus',
  wav:  'audio/wav',
  flac: 'audio/flac',
  weba: 'audio/webm',
  wasm: 'application/wasm',
  wat:  'text/plain;charset=utf-8',
  glsl: 'text/plain;charset=utf-8',
  vert: 'text/plain;charset=utf-8',
  frag: 'text/plain;charset=utf-8',
  wgsl: 'text/wgsl;charset=utf-8',
  ktx:  'image/ktx',
  ktx2: 'image/ktx2',
  gltf: 'model/gltf+json',
  glb:  'model/gltf-binary',
  obj:  'model/obj',
  mtl:  'model/mtl',
  stl:  'model/stl',
  ply:  'application/octet-stream',
  usdz: 'model/vnd.usdz+zip',
  psd:  'image/vnd.adobe.photoshop',
  psb:  'image/vnd.adobe.photoshop',
  ai:   'application/postscript',
  eps:  'application/postscript',
  py:   'text/x-python;charset=utf-8',
  pyw:  'text/x-python;charset=utf-8',
  rb:   'text/x-ruby;charset=utf-8',
  go:   'text/x-go;charset=utf-8',
  rs:   'text/x-rust;charset=utf-8',
  java: 'text/x-java-source;charset=utf-8',
  cs:   'text/plain;charset=utf-8',
  swift: 'text/x-swift;charset=utf-8',
  kt:   'text/x-kotlin;charset=utf-8',
  dart: 'text/x-dart;charset=utf-8',
  lua:  'text/x-lua;charset=utf-8',
  sql:  'application/sql;charset=utf-8',
  sh:   'application/x-sh;charset=utf-8',
  bash: 'application/x-sh;charset=utf-8',
  zsh:  'application/x-sh;charset=utf-8',
};

export function guessMimeType(name: string): string | undefined {
  const dot = name.lastIndexOf('.');
  if (dot === -1 || dot === name.length - 1) {
    return isTextSourcePath(name) ? 'text/plain;charset=utf-8' : undefined;
  }
  const ext = name.slice(dot + 1).toLowerCase();
  return MIME_BY_EXT[ext] ?? (isTextSourcePath(name) ? 'text/plain;charset=utf-8' : undefined);
}
